# Generated by Django 5.2.1 on 2025-05-21 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyect',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
