# Generated by Django 5.2.1 on 2025-05-22 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_alter_proyect_options_proyect_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyect',
            name='url',
        ),
        migrations.AddField(
            model_name='proyect',
            name='link',
            field=models.URLField(blank=True, null=True, verbose_name='Direccion Web'),
        ),
    ]
